# Generated by Django 4.0.1 on 2022-01-11 23:32

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questions_options_answers'),
        ('tags', '0003_customanswertag_answertagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.AnswerTagged', to='tags.CustomAnswerTag', verbose_name='Tags'),
        ),
    ]
