# Generated by Django 4.0.1 on 2022-01-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_answers_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
    ]
