# Generated by Django 4.0.1 on 2022-01-11 23:41

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_customanswertag_answertagged'),
        ('questions', '0006_questions_slug_alter_questions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.AnswerTagged', to='tags.CustomAnswerTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags.Tagged', to='tags.CustomTag', verbose_name='Tags'),
        ),
    ]
