# Generated by Django 4.0.1 on 2022-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_answers_tags_alter_questions_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='total_vote_count',
            field=models.IntegerField(default=0, verbose_name='Total Vote Count'),
        ),
        migrations.AddField(
            model_name='questions',
            name='total_vote_count',
            field=models.IntegerField(default=0, verbose_name='Total Vote Count'),
        ),
    ]
