# Generated by Django 4.0.1 on 2022-01-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('featured', models.BooleanField(default=False)),
                ('similar_tag', models.ManyToManyField(blank=True, to='tags.CustomTag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
